### ISSUE TITLE
enable plugin meet error

### ISSUE THREAD

**Issue by Ramos-dev** [palantir/stash-codesearch-plugin#19]
I upgrade pom.xml to stash version 3.7.1, and run mvn clean package。When I install and  enable It,I met that error：
![image](https://user-images.githubusercontent.com/30281131/47634479-a716e500-db8c-11e8-9284-2805c5bbbe65.png)

logs：
`com.atlassian.plugin.osgi.container.OsgiContainerException: Cannot start plugin: com.palantir.stash.stash-code-search
       at com.atlassian.plugin.osgi.factory.OsgiPlugin.enableInternal(OsgiPlugin.java:479) ~[atlassian-plugins-osgi-3.2.15.jar:na]
       at com.atlassian.plugin.impl.AbstractPlugin.enable(AbstractPlugin.java:310) ~[atlassian-plugins-core-3.2.15.jar:na]
       at com.atlassian.plugin.manager.PluginEnabler.actualEnable(PluginEnabler.java:136) [atlassian-plugins-core-3.2.15.jar:na]
       at com.atlassian.plugin.manager.PluginEnabler.enable(PluginEnabler.java:104) [atlassian-plugins-core-3.2.15.jar:na]
       at com.atlassian.plugin.manager.PluginEnabler.enableAllRecursively(PluginEnabler.java:71) [atlassian-plugins-core-3.2.15.jar:na]
       at com.atlassian.plugin.manager.DefaultPluginManager.enablePlugins(DefaultPluginManager.java:1760) [atlassian-plugins-core-3.2.15.jar:na]
       at com.atlassian.stash.internal.plugin.ClusteredPluginController.enablePlugins(ClusteredPluginController.java:54) [stash-platform-3.7.1.jar:na]
       at com.atlassian.upm.core.impl.PluginEnablementServiceImpl$1.doInTransaction(PluginEnablementServiceImpl.java:84) [atlassian-universal-plugin-manager-plugin-2.18.2_1475106120000.jar:na]
       at com.atlassian.upm.core.impl.PluginEnablementServiceImpl$1.doInTransaction(PluginEnablementServiceImpl.java:60) [atlassian-universal-plugin-manager-plugin-2.18.2_1475106120000.jar:na]
       at com.atlassian.sal.core.transaction.HostContextTransactionTemplate$1.doInTransaction(HostContextTransactionTemplate.java:25) [sal-core-2.13.3.jar:na]
       at com.atlassian.stash.internal.sal.spi.HostContextAccessorImpl.doInTransaction(HostContextAccessorImpl.java:27) [stash-platform-3.7.1.jar:na]
       at com.atlassian.sal.core.transaction.HostContextTransactionTemplate.execute(HostContextTransactionTemplate.java:21) [sal-core-2.13.3.jar:na]
       at com.atlassian.upm.core.impl.PluginEnablementServiceImpl.enablePlugin(PluginEnablementServiceImpl.java:59) [atlassian-universal-plugin-manager-plugin-2.18.2_1475106120000.jar:na]
       at com.atlassian.upm.core.rest.resources.PluginResource.put(PluginResource.java:131) [atlassian-universal-plugin-manager-plugin-2.18.2_1475106120000.jar:na]
       at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.5_1475106120000.jar:na]
       at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:99) [StashAuthenticationFilter.class:na]
       at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:111) [BeforeLoginPluginAuthenticationFilter.class:na]
       at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:77) [BeforeLoginPluginAuthenticationFilter.class:na]
       at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:100) [atlassian-trusted-apps-core-3.0.8.jar:na]
       at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.10_1475106120000.jar:na]
       at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:32) [analytics-client-3.56_1475106120000.jar:na]
       at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.56_1475106120000.jar:na]
       at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:89) [BeforeLoginPluginAuthenticationFilter.class:na]
       at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
       at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) [stash-service-impl-3.7.1.jar:na]
       at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
       at com.meituan.jmonitor.collector.http.HttpMonitorFilter.doFilter(HttpMonitorFilter.java:54) [jmonitor-1.4.9.jar:1.4.9]
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
       at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
       ... 305 frames trimmed
Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle com.palantir.stash.stash-code-search [103]: Unable to resolve 103.0: missing requirement [103.0] package; (package=com.palantir.stash.codesearch.admin)
       at org.apache.felix.framework.Felix.resolveBundle(Felix.java:3564) ~[org.apache.felix.framework-3.2.2.jar:na]`

**Comment by Ramos-dev** [comment]
@mud @bavardage @hxu @j-baker
